name: hoarder

services:
  hoarder:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION}
    container_name: hoarder
    restart: unless-stopped
    volumes:
      - hoarder_data:/data
    ports:
      - "3100:3000"
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
    networks:
      - hoarder_network

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: hoarder_chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - hoarder_network

  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    container_name: hoarder_meilisearch
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - hoarder_meilisearch_data:/meili_data
    networks:
      - hoarder_network

volumes:
  hoarder_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volumes/hoarder_data

  hoarder_meilisearch_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volumes/hoarder_meilisearch_data

networks:
  hoarder_network:
    driver: bridge
    name: hoarder_network
