services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    container_name: portainer
    ports:
      - "${PORTAINER_UI_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    networks:
      - portainer_network

volumes:
  portainer_data:
    name: portainer_data

networks:
  portainer_network:
    driver: bridge
    name: portainer_network
