---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Dev Ops:
    - Homepage:
        - icon: homepage
          href: https://github.com/gregrossdev/docker-stacks/tree/homepage/homepage
          description: Homepage directory on GitHub
    - Hoarder:
        - icon: hoarder
          href: https://hoarder.homelab.gregross.dev
          description: Self-hosted bookmarking app
    - N8N:
        - icon: n8n
          href: https://n8n.homelab.gregross.dev
          description: Automation workflow platform
    - Vaultwarden:
        - icon: vaultwarden
          href: https://passwords.homelab.gregross.dev
          description: Self-hosted password manager


- Life Ops:
    - Todoist:
        - icon: todoist
          href: https://todoist.com/
          description: Task management and daily planning
    - Notion:
        - icon: notion
          href: https://notion.so/
          description: Projects, notes, and writing ideas
   
