---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Life Ops:
    - Todoist:
        - icon: todoist
          href: https://todoist.com/
          description: Task management and daily planning
    - Notion:
        - icon: todoist
          href: https://notion.so/
          description: Projects, notes, and writing ideas
- Dev Ops:
    - Github:
        - icon: github
          href: https://github.com/gregrossdev/docker-stacks
          description: Homelab Repo
