---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Dev Ops:
    - Homepage:
        - icon: github
          href: https://github.com/gregrossdev/docker-stacks/tree/homepage/homepage
          description: Homepage directory on GitHub

- Life Ops:
    - Todoist:
        - icon: todoist
          href: https://todoist.com/
          description: Task management and daily planning
    - Notion:
        - icon: notion
          href: https://notion.so/
          description: Projects, notes, and writing ideas
