---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Dev Ops:
    - Github:
        - icon: github
          href: https://github.com/gregrossdev/docker-stacks
          description: Homelab Repo
    - Homepage:
        - icon: homepage
          href: https://github.com/gregrossdev/docker-stacks/tree/homepage/homepage
          description: Homepage directory on GitHub
    - Hoarder:
        - icon: hoarder
          href: https://hoarder.homelab.gregross.dev
          description: Self-hosted bookmarking app

- Life Ops:
    - Todoist:
        - icon: todoist
          href: https://todoist.com/
          description: Task management and daily planning
    - Notion:
        - icon: notion
          href: https://notion.so/
          description: Projects, notes, and writing ideas
    - WEEon:
        - icon: notion
          href: https://notion.so/
          description: Projects, notes, and writing ideas
   
